INSERT INTO cards (name, image, level, type, rarity) VALUES
  ('Caballero Dragón', 'https://example.com/images/dragon-knight.png', 5, 'Unidad', 'Épica'),
  ('Bola de Fuego', 'https://example.com/images/fireball.png', 2, 'Hechizo', 'Común'),
  ('Arquera Elfa', 'https://example.com/images/elf-archer.png', 3, 'Unidad', 'Rara'),
  ('Muro de Piedra', 'https://example.com/images/stone-wall.png', 1, 'Defensa', 'Común'),

INSERT INTO rarities (name) VALUES
  ('Common'),
  ('Rare'),
  ('SR'),
  ('UR'),
  ('Ultimate'),
  ('Collector'),
  ('Secret'),
  ('Starlight'),
  ('QCR'),
  ('Ghost'),
  ('Gold'),

  INSERT INTO types (name) VALUES
  ('Aqua'),
  ('Beast'),
  ('Beast-Warrior'),
  ('Creator God'),
  ('Cyberse'),
  ('Dinosaur'),
  ('Divine-Beast'),
  ('Dragon'),
  ('Fairy'),
  ('Fiend'),
  ('Fish'),
  ('Insect'),
  ('Illusion'),
  ('Machine'),
  ('Plant'),
  ('Reptile'),
  ('Rock'),
  ('Sea Serpent'),
  ('Spellcaster'),
  ('Thunder'),
  ('Warrior'),
  ('Winged Beast'),
  ('Wyrm'),
  ('Zombie'),